In [3]:
my_list = [1,2,3]

In [4]:
import numpy as np

In [6]:
arr = np.array(my_list)

In [8]:
arr

array([1, 2, 3])

In [15]:
my_mat = [[1,2,3], [4,5,6], [7,8,9]]

In [19]:
two_arr = np.array(my_mat)

In [20]:
two_arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [49]:
np.arange(0,10,2)

array([0, 2, 4, 6, 8])

In [24]:
np.zeros(3)

array([0., 0., 0.])

In [27]:
np.zeros((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [31]:
np.ones(4)

array([1., 1., 1., 1.])

In [34]:
np.linspace(0,5,100)

array([0.        , 0.05050505, 0.1010101 , 0.15151515, 0.2020202 ,
       0.25252525, 0.3030303 , 0.35353535, 0.4040404 , 0.45454545,
       0.50505051, 0.55555556, 0.60606061, 0.65656566, 0.70707071,
       0.75757576, 0.80808081, 0.85858586, 0.90909091, 0.95959596,
       1.01010101, 1.06060606, 1.11111111, 1.16161616, 1.21212121,
       1.26262626, 1.31313131, 1.36363636, 1.41414141, 1.46464646,
       1.51515152, 1.56565657, 1.61616162, 1.66666667, 1.71717172,
       1.76767677, 1.81818182, 1.86868687, 1.91919192, 1.96969697,
       2.02020202, 2.07070707, 2.12121212, 2.17171717, 2.22222222,
       2.27272727, 2.32323232, 2.37373737, 2.42424242, 2.47474747,
       2.52525253, 2.57575758, 2.62626263, 2.67676768, 2.72727273,
       2.77777778, 2.82828283, 2.87878788, 2.92929293, 2.97979798,
       3.03030303, 3.08080808, 3.13131313, 3.18181818, 3.23232323,
       3.28282828, 3.33333333, 3.38383838, 3.43434343, 3.48484848,
       3.53535354, 3.58585859, 3.63636364, 3.68686869, 3.73737

In [38]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [39]:
np.random.rand(5)

array([0.9725618 , 0.45236509, 0.72194649, 0.30724136, 0.24668308])

In [41]:
np.random.rand(5,5)

array([[0.34352265, 0.51307686, 0.37734668, 0.78071014, 0.37816831],
       [0.19379589, 0.3052006 , 0.18995132, 0.92028395, 0.21274828],
       [0.34672193, 0.41168311, 0.79753341, 0.14659949, 0.1183978 ],
       [0.59867127, 0.43415792, 0.9673139 , 0.02763829, 0.43842659],
       [0.96152988, 0.12208697, 0.22246271, 0.86997342, 0.64580214]])

In [45]:
np.random.randn(5,5)

array([[ 2.29321783,  2.93739027, -0.18499151,  1.30295358,  0.0178695 ],
       [ 1.42709005, -0.247565  , -2.23909581, -0.75751038,  0.20949132],
       [-0.17938039, -0.42170986,  0.8705136 ,  0.59716695,  0.81422012],
       [-0.44967917, -2.10428749,  0.86221017, -1.44849254,  1.0846366 ],
       [ 0.31284857, -0.08463091,  1.93010648,  0.06827699,  1.34554258]])

In [47]:
np.random.randint(0,10,100)

array([3, 3, 0, 2, 2, 0, 3, 0, 7, 4, 4, 6, 5, 5, 3, 6, 2, 7, 5, 7, 0, 7,
       8, 8, 3, 0, 4, 9, 5, 5, 1, 9, 7, 5, 9, 5, 3, 1, 1, 1, 2, 1, 7, 6,
       5, 7, 0, 4, 6, 7, 8, 0, 1, 9, 1, 6, 5, 0, 3, 3, 9, 6, 0, 3, 8, 3,
       6, 1, 2, 8, 0, 7, 6, 7, 0, 2, 4, 1, 8, 7, 0, 7, 0, 8, 7, 8, 1, 9,
       9, 1, 0, 6, 3, 4, 3, 5, 1, 6, 5, 2])